### PR TITLE
KNN imputor fixes

### LINKED ISSUE #73: KNN tests sometimes fail
Need to look into why the KNN tests sometimes fail or improve the synthetic data generation algorithm.

https://travis-ci.com/github/invenia/Impute.jl/jobs/394511915

### PR DESCRIPTION
**Pull request by rofinn**
1. Fixes bug with fallback check for missing neighbors using `ismissing` on impute data, so it would never identify missing neighbors. Example, https://codecov.io/gh/invenia/Impute.jl/src/2f64a27010480692aff4077792e92ce5b5c01bc0/src/imputors/knn.jl
2. Missing neighbors are only those that have a missing value that's of interest to us.
3. Inverse distance weighting is simplified to the weighted mean using `weights` from StatsBase.
4. Continues to build the `KDTree` from full dataset, but reduces points searched for to those observations containing `missings`.
5. Closes #73 by running simulated Iris missing patterns 1000 times (similar to referenced paper) and using Welch's t-test to determine "significance" 🤞  

The end result is that the iris dataset tests aren't much better, but the new code allocates less memory, is faster and performs and order of magnitude better on the "Data match" tests that we expect it to do well on.

Before:
```
knn_nrmsd = 0.02351386140235716
mean_nrmsd = 0.025655653575507923
knn_nrmsd = 0.03454405384070915
mean_nrmsd = 0.036899643641953625
knn_nrmsd = 0.04029575884706388
mean_nrmsd = 0.042321570291156005
knn_nrmsd = 0.00270435447793449
mean_nrmsd = 0.008769967721453583
```

After:
```
knn_nrmsd = 0.034385695023072295
mean_nrmsd = 0.03848092187638184
knn_nrmsd = 0.04448270841439509
mean_nrmsd = 0.04616687082955499
knn_nrmsd = 0.05125571112635573
mean_nrmsd = 0.05261488365411982
knn_nrmsd = 0.00037746930884156415
mean_nrmsd = 0.004039809809703139
```

Before:
```
julia> @benchmark Impute.knn($X; k=4, dims=:rows)
BenchmarkTools.Trial:
  memory estimate:  200.77 MiB
  allocs estimate:  1095761
  --------------
  minimum time:     147.330 ms (12.08% GC)
  median time:      157.492 ms (18.28% GC)
  mean time:        168.883 ms (23.04% GC)
  maximum time:     323.553 ms (57.92% GC)
  --------------
  samples:          30
  evals/sample:     1

```

After:
```
julia> @benchmark Impute.knn($X; k=4, dims=:rows)
BenchmarkTools.Trial:
  memory estimate:  33.29 MiB
  allocs estimate:  711148
  --------------
  minimum time:     57.409 ms (0.00% GC)
  median time:      63.676 ms (5.84% GC)
  mean time:        65.398 ms (4.66% GC)
  maximum time:     90.936 ms (5.13% GC)
  --------------
  samples:          77
  evals/sample:     1
```

### CODE REVIEW

**Comment by rofinn** [comment]
@appleparan

File: src/imputors/knn.jl [hunk 1]
```diff
@@ -34,40 +34,50 @@ function impute!(data::AbstractMatrix{Union{T, Missing}}, imp::KNN; dims=nothing
     X = d == 1 ? data : transpose(data)
 
     # Get mask array first
-    mmask = ismissing.(X)
+    Xmask = ismissing.(X)
```
Comment (oxinabox) [inline src/imputors/knn.jl:37]: why not `X_mask`?
Isn't that more inline with BlueStyle?

File: src/imputors/knn.jl [hunk 2]
```diff
@@ -34,40 +34,50 @@ function impute!(data::AbstractMatrix{Union{T, Missing}}, imp::KNN; dims=nothing
...
 
-    # fill missing value as mean value
+    # Fill missing value as mean value
     impute!(X, Substitute(); dims=1)
 
     # Disallow `missings` for NearestNeighbors
     X = disallowmissing(X)
 
+    # Our search points are just observations containing `missing`s
+    points = X[:, vec(reduce(|, Xmask; dims=1))]
```
Comment (oxinabox) [inline src/imputors/knn.jl:46]:
```suggestion
    points = X[:, vec(any(Xmask; dims=1))]
```

I wonder if this could be a view
```suggestion
    points = @view X[:, vec(any(Xmask; dims=1))]
```
and if so what the effect that would have on performance.

File: src/imputors/knn.jl (hunk 1 above)
Comment (oxinabox) [reply src/imputors/knn.jl:37]: Also I wonder if we should call this `missing_mask`?
So i don't have to remember if it was a mask of missings or nonmissing?

File: src/imputors/knn.jl [hunk 3]
```diff
@@ -34,40 +34,50 @@ function impute!(data::AbstractMatrix{Union{T, Missing}}, imp::KNN; dims=nothing
...
+    #   location in the original dataset.
+    for (idx, dist) in zip(NearestNeighbors.knn(kdtree, points, imp.k, true)...)
+        # Our closest neighbor should always be our input data point (distance of zero)
+        @assert iszero(first(dist))
+
+        # Location of point to impute
+        j = first(idx)
+
+        # Update each missing value in this point
+        for i in 1:size(points, 1)
```
Comment (oxinabox) [inline src/imputors/knn.jl:64]:
```suggestion
        for i in axes(points, 1)
```
for things with weird axes

File: src/imputors/knn.jl [hunk 4]
```diff
@@ -34,40 +34,50 @@ function impute!(data::AbstractMatrix{Union{T, Missing}}, imp::KNN; dims=nothing
...
+            # Skip if there are too many missing neighbor values
+            (count(nmask) / imp.k) > imp.threshold && continue
+
+            # Weight valid neighbors based on inverse distance
+            wv = weights(1.0 ./ dist[.!nmask])
+
+            # Only fill with the weighted mean of neighbors if the sum of the weights are
+            # non-zero and finite.
+            if isfinite(sum(wv)) && !iszero(sum(wv))
+                X[i, j] = mean(X[i, idx[.!nmask]], wv)
```
Comment (oxinabox) [inline src/imputors/knn.jl:80]:
```suggestion
                X[i, j] = @views mean(X[i, idx[.!nmask]], wv)
```

**Review by oxinabox — APPROVED** [review]

File: src/imputors/knn.jl (hunk 1 above)
Comment (rofinn) [reply src/imputors/knn.jl:37]: I didn't see anything explicit about variables names, just method names. I don't think this package follows BlueStyle anyways since this predates that guide. I can change it for now, but I think we should have a separate BlueStyle PR, to avoid inconsistencies within this package.

File: src/imputors/knn.jl (hunk 2 above)
Comment (rofinn) [reply src/imputors/knn.jl:46]: I tried adding `@view` and `@views` calls to all the indexing/slicing calls and it doesn't seem to make much of a difference.

```
julia> @benchmark Impute.knn($X; k=4, dims=:rows)
BenchmarkTools.Trial:
  memory estimate:  33.52 MiB
  allocs estimate:  686426
  --------------
  minimum time:     58.834 ms (0.00% GC)
  median time:      65.528 ms (6.23% GC)
  mean time:        68.600 ms (5.33% GC)
  maximum time:     98.741 ms (13.55% GC)
  --------------
  samples:          73
  evals/sample:     1
```

I guess that makes sense because all of our slices should be a fraction of the size of the original array under normal circumstances (e.g., < 25% missing data, k < 10). My guess is that the overhead of the view outweighs the benefits for relatively small subarrays? I'm also not sure what operations the `NearestNeighbors.knn` call is doing, but those might be less performance for subarrays. I could try benchmarking more extreme cases with more missing values or considering more neighbors, but I don't know how useful that'll be?

Comment (rofinn) [reply src/imputors/knn.jl:46]: I think the big performance gain with this PR is with reducing the number of search `points` under normal circumstances.

File: src/imputors/knn.jl (hunk 1 above)
Comment (rofinn) [reply src/imputors/knn.jl:37]: I was considering using `missing_mask`, but that seemed a bit verbose when doing our indexing/slicing. I can just do the slicing on separate lines though 🤷

**Comment by rofinn** [comment]
All review comments applied except from `@view`/`@views` since there wasn't a clear performance benefit during quick benchmarking. I'll merge when tests pass.

**Comment by appleparan** [comment]
That's good! Thanks!
