### PR TITLE
Imputor TestSuites

### LINKED ISSUE #45: lcof MethodErrors if everything is missing
```
using Impute
df = DataFrame(X=[missing, missing])
Impute.locf(df)
```

### output
```
MethodError: no method matching +(::Nothing, ::Int64)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  +(!Matched::Complex{Bool}, ::Real) at complex.jl:292
  +(!Matched::Missing, ::Number) at missing.jl:97
  ...

Stacktrace:
 [1] (::getfield(Impute, Symbol("##50#51")){Array{Missing,1}})(::Impute.Context) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors/locf.jl:43
 [2] (::Impute.Context)(::getfield(Impute, Symbol("##50#51")){Array{Missing,1}}) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/context.jl:227
 [3] impute!(::Array{Missing,1}, ::Impute.LOCF) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors/locf.jl:42
 [4] impute!(::DataFrame, ::Impute.LOCF) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors.jl:163
 [5] #impute#17 at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors.jl:76 [inlined]
 [6] impute at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors.jl:76 [inlined]
 [7] _impute(::DataFrame, ::Type{Impute.LOCF}) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/imputors.jl:58
 [8] #locf#120 at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/Impute.jl:92 [inlined]
 [9] locf(::DataFrame) at /Users/oxinabox/.julia/packages/Impute/EgPBk/src/Impute.jl:92
 [10] top-level scope at In[95]:2
```

### LINKED ISSUE #46: TestSuites
It'd be nice if we could have testsuites that throw a bunch of different cases at the Imputor types to check for error conditions w/o needing to know the imputation mechanism.

### PR DESCRIPTION
**Pull request by rofinn**
- Use TestSuites to avoid mostly duplicated tests for each Imputor type (closes #46)
- Fixes some error conditions with completely missing datasets (closes #45)
- Fixes ambiguity errors when using rowtables
- Fixes deprecation of GroupedDataFrame broadcasting on 0.19.2

TODO:
- [x] Cleanup existing tests that duplicate behaviour from the testsuites
- ~~[ ] Test chains in the testsuite~~
- [x] Add tests for dataframe groupby

### CODE REVIEW

File: src/imputors/fill.jl [hunk 1]
```diff
@@ -34,11 +34,17 @@ end
...
-function impute!(data::AbstractVector, imp::Fill)
+function _impute!(data::AbstractVector, imp::Fill)
     imp.context() do c
         fill_val = if isa(imp.value, Function)
-            # Call `deepcopy` because we can trust that it's available for all types.
-            imp.value(Impute.drop(data; context=c))
+            available = Impute.drop(data; context=c)
+
+            if isempty(available)
+                @warn "Cannot apply fill function $(imp.value) as all values are missing"
```
Comment (oxinabox) [inline src/imputors/fill.jl]: It is annoying having this at warn level.
Often it is fine. 
So I think it should be at debug level.

One can always use `LoggingExtras.TransformLogger` to bump it up.

File: test/testutils.jl [hunk 2]
```diff
@@ -0,0 +1,330 @@
...
+struct ImputorTester{I<:Imputor}
+    imp::Type{I}
+    f::Function
+    f!::Function
+    kwargs::Dict
+end
+
+function ImputorTester(imp::Type{<:Imputor}; kwargs...)
+    fname = lowercase(string(nameof(imp)))
+    settings = Dict(kwargs...)
```
Comment (oxinabox) [inline test/testutils.jl]: Why are these mutable? Why not just make the Kwargs be `settings` and leave it in its named tuple?

File: test/testutils.jl [hunk 3]
```diff
@@ -0,0 +1,330 @@
...
+        end
+
+        @testset "Too many missing values" begin
+            # Test Context error condition
+            c = DataFrame(
+                :sin => fill(missing, 10),
+                :cos => fill(missing, 10),
+            )
+            settings = deepcopy(tester.kwargs)
+            settings[:context] = Context(; limit=0.1)
```
Comment (oxinabox) [inline test/testutils.jl]: `tester.kwargs` should be a NamedTuple, and you should overwrite context via `merge(tester.kwargs, (; context=...))`

File: test/testutils.jl [hunk 4]
```diff
@@ -0,0 +1,330 @@
+
+struct ImputorTester{I<:Imputor}
+    imp::Type{I}
+    f::Function
+    f!::Function
+    kwargs::Dict
+end
+
+function ImputorTester(imp::Type{<:Imputor}; kwargs...)
```
Comment (oxinabox) [inline test/testutils.jl]: Can we have a docstring listing all the Kwargs?

File: test/testutils.jl [hunk 5]
```diff
@@ -0,0 +1,330 @@
...
+
+function test_columntable(tester::ImputorTester)
+    @testset "Column Table" begin
+        table = DataFrame(
+            :sin => allowmissing(sin.(1.0:1.0:20.0)),
+            :cos => allowmissing(sin.(1.0:1.0:20.0)),
+        )
+
+        table.sin[[2, 3, 7, 12, 19]] .= missing
+        coltab = Tables.columntable(table)
```
Comment (oxinabox) [inline test/testutils.jl]: I can recall if this will convert a DataFrame to a "canonical" column table. (I.e a Named Tuple of Vectors)
Or if it will be a no-op.

Either way something is wrong.
Either should not have created the DataFrame to begin with,or should not have done this line.

Though it might be nice to test both.

**Comment by rofinn** [comment]
Thanks for taking a look over it before you leave.

File: Project.toml [hunk 6]
```diff
@@ -4,6 +4,7 @@ authors = ["Invenia Technical Computing"]
 version = "0.3.0"
 
 [deps]
+DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
```
[the remark this answers is not in the document]
Comment (rofinn) [reply Project.toml]: No, I'm must have accidentally don't a `git commit -a`. I'll revert before removing the WIP.

File: src/imputors/fill.jl (hunk 1 above)
Comment (rofinn) [reply src/imputors/fill.jl]: Sure. I wasn't 100% on the warning anyways.

File: test/testutils.jl (hunk 3 above)
Comment (rofinn) [reply test/testutils.jl]: :+1 `merge` is definitely the better solution than having it be a `Dict`

File: test/testutils.jl (hunk 4 above)
Comment (rofinn) [reply test/testutils.jl]: The issue is that the kwargs will vary based on the Imputor type.

File: test/testutils.jl (hunk 5 above)
Comment (rofinn) [reply test/testutils.jl]: This was a holdover from the old tests. I should just construct a named tuple of arrays instead of a dataframe here.

File: test/testutils.jl (hunk 2 above)
Comment (rofinn) [reply test/testutils.jl]: FWIW, kwargs isn't a namedtuple, but yes, a namedtuple would work better.

**Comment by rofinn** [comment]
@oxinabox Do you have any more comments? I'd like to get this in before I do an more refactoring.
